---
# Ansible Collections requeridas para el proyecto
collections:
  - name: community.vmware
    version: ">=3.0.0"
  
  - name: cisco.ios
    version: ">=4.0.0"
  
  - name: ansible.netcommon
    version: ">=5.0.0"
  
  - name: ansible.posix
    version: ">=1.5.0"
  
  - name: ansible.utils
    version: ">=2.0.0"
