---
all:
  children:
    esxi:
      hosts:
        esxi-vmware-host:
          ansible_host: 172.17.25.1
          ansible_connection: local
          vcenter_hostname: 172.17.25.1
          vcenter_username: root
          vcenter_password: "qwe123$"
          vcenter_port: 443
          vcenter_validate_certs: no
          datacenter: ha-datacenter
          datastore: datastore1

          
    vm_router:
      hosts:
        debian-router:
          ansible_host: "2025:db8:220::1"
          ansible_user: ansible
          ansible_connection: ssh
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          vm_name: vm-debian-router
          vm_template: "Debian 12 Template"
          vm_folder: "/vm"
          cdrom: "datastore1:debian/debian-12.12.0-amd64-netinst.iso"
          networks:
            - name: Red Fernandez
              type: static
              ipv6_address: "2025:db8:220::1"
              ipv6_prefix: "64"
          ports:
            - "80/tcp"
            - "22/tcp"
            
    vm_hosts:
      hosts:
        ubuntu-pc:
          ansible_host: "2025:db8:220::10"
          ansible_user: ansible
          ansible_connection: ssh
          vm_name: vm-ubuntu-pc
          vm_template: "Ubuntu 22.04 Template"
          vm_folder: "/vm"
          cdrom: "datastore1:ubuntu/ubuntu-24.04.2-desktop-amd64.iso"
          networks:
            - name: Red Fernandez
              type: slaac
              ipv6_address: "2025:db8:220::10"
              ipv6_prefix: "64"
              
        windows-pc:
          ansible_host: "2025:db8:220::11"
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_transport: basic
          vm_name: vm-windows-pc
          vm_template: "Windows Server 2022 Template"
          vm_folder: "/vm"
          cdrom: "datastore1:W-11/Win11_24H2_Spanish_x64.iso"
          networks:
            - name: Red Fernandez
              type: slaac
              ipv6_address: "2025:db8:220::11"
              ipv6_prefix: "64"
              
    ios_routers:
      hosts:
        ios-core-router:
          ansible_host: "2025:db8:101::1"
          ansible_user: cisco
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          hostname: CORE-ROUTER-101
          interfaces:
            - name: GigabitEthernet0/0
              description: "Uplink to Backbone"
              ipv6_address: "2025:db8:101::1"
              ipv6_prefix: "64"
            - name: GigabitEthernet0/1
              description: "Link to VMware VLAN 220"
              ipv6_address: "2025:db8:101::a2"
              ipv6_prefix: "64"
              vlan: 220
              
    ios_switches:
      hosts:
        access-switch:
          ansible_host: "2025:db8:101::2"
          ansible_user: cisco
          ansible_connection: network_cli
          ansible_network_os: ios
          hostname: SW-ACCESS-220
          management_ipv6: "2025:db8:101::2/64"
          management_vlan: 101
          vlan_interfaces:
            - id: 220
              name: "VMware-220"
              ipv6_address: "2025:db8:220::2"
              ipv6_prefix: "64"
          access_ports:
            - port: "GigabitEthernet1/0/1"
              vlan: 220
              description: "VM router uplink"
            - port: "GigabitEthernet1/0/2"
              vlan: 220
              description: "VM hosts"
          trunk_ports:
            - port: "GigabitEthernet1/0/24"
              vlans: [101, 220]
              description: "Trunk to core"
              
    all_vms:
      children:
        vm_router:
        vm_hosts:
        
    all_ios:
      children:
        ios_routers:
        ios_switches: