---
all:
  children:
    esxi:
      hosts:
        esxi-vmware-host:
          ansible_host: "172.17.25.1"  # IP real del ESXi (red local)
          ansible_connection: local
          vcenter_hostname: "{{ vault_vcenter_hostname | default('172.17.25.1') }}"
          vcenter_username: "{{ vault_vcenter_username | default('root') }}"
          vcenter_password: "{{ vault_vcenter_password | default('qwe123$') }}"
          vcenter_port: "{{ vault_vcenter_port | default(443) }}"
          vcenter_validate_certs: "{{ vault_vcenter_validate_certs | default(false) }}"
          datacenter: ha-datacenter
          datastore: datastore1

    debian_router:
      hosts:
        debian-router:
          # --- Conexión Ansible --- #
          # IP de gestión fija para el router.
          ansible_host: "172.17.25.122"
          ansible_user: ansible
          ansible_connection: ssh
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_flags: '-S'
          ansible_ssh_timeout: 5
          ansible_timeout: 10

          # --- Configuración de VM ---
          vm_name: vm-debian-router
          
          # --- Configuración APT ---
          apt_force_ipv4: false  # No forzar IPv4 para APT ya que queremos usar IPv6
          # La VM debe tener 2 interfaces: una en 'VM Network' y otra en 'Red Fernandez'
          networks:
            - name: VM Network # Interfaz WAN/Gestión
            - name: Red Fernandez

          # --- Interfaz WAN (y Gestión) ---
          # Configuración inicial para permitir la conexión de Ansible
          ansible_initial_ip: "172.17.25.122"  # IP de gestión

          # Configuración final de WAN
          wan_method: "static"  # Método de configuración: 'dhcp' o 'static'
          wan_interface: ens192  # Interfaz WAN/Gestión

          # --- Interfaz LAN ---
          # Conectada a "Red Fernandez". Da servicio a las VMs del laboratorio.
          lan_interface: ens34   # Interfaz LAN (Red Fernandez)
          lan_ipv6_address: "2025:db8:101::1"
          lan_ipv6_prefix: 64

          # --- Servicios en la LAN ---
          # radvd y dhcpv6 para la subred 2025:DB8:101::/64 (UNIFICADA)
          radvd_prefix: "2025:db8:101::/64"
          dhcpv6_subnet: "2025:db8:101::"
          dhcpv6_prefix: 64
          dhcpv6_range_start: "2025:db8:101::10"
          dhcpv6_range_end: "2025:db8:101::50"
          dhcpv6_dns_servers:
            - "2001:4860:4860::8888"
            - "2001:4860:4860::8844"
          # Rutas estáticas IPv6 persistentes que se aplicarán en /etc/network/interfaces
          static_routes:
            - network: "2025:db8:100::/64"
              via: "2025:db8:101::2"  # Vía router físico

    vm_hosts:
      hosts:
        ubuntu-pc:
          # Usar debian-router como 'jump host' para alcanzar esta VM
          # ======================================================================
          # IP TEMPORAL: Usamos la IP actual de la máquina (obtenida por SLAAC)
          # para poder conectarnos y configurarla para que use la IP final (::10).
          ansible_host: "2025:db8:101::4c"
          ansible_ssh_common_args: "-o ProxyCommand=\"ssh -W %h:%p -q ansible@{{ hostvars['debian-router']['ansible_host'] }}\""
          networks:
            - name: Red Fernandez
              type: dhcpv6  # Obtiene IP del Debian Router
              ipv6_expected: "2025:db8:101::10" # IP corta esperada del DHCP
              ipv6_prefix: "64"

        windows-pc:
          networks:
            - name: Red Fernandez
              type: dhcpv6  # Obtiene IP del Debian Router
              ipv6_expected: "2025:db8:101::11" # IP corta esperada del DHCP
              ipv6_prefix: "64"

      vars:
        ansible_user: ansible
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_transport: basic

    # ==========================================
    # DISPOSITIVOS DE RED (IOS/Network CLI)
    # ==========================================
    network_devices:
      children:
        ios_routers:
        ios_switches:
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "ansible"
        ansible_password: "Ansible123!"
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: "Ansible123!"
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ansible_command_timeout: 60
        ansible_connect_timeout: 60

    ios_routers:
      hosts:
        # Router físico del laboratorio
        physical-router:
          ansible_host: "2025:db8:101::2"  # Acceso por IPv6 (interfaz G0/0/1)
          hostname: "Router-Lab"
          interfaces: "{{ physical_router_interfaces }}"
          static_routes:
            - network: "2025:db8:101::/64"
              via: "2025:db8:101::1"  # Ruta hacia debian-router
            - network: "2025:db8:100::/64"
              via: "2025:db8:100::1"  # Ruta local (connected)

    ios_switches:
      hosts:
        # NOTA: switch-3 es un puente L2 transparente sin gestión IP
        # No requiere configuración via Ansible - funciona como switch no gestionado

    # ==========================================
    # SERVIDORES LINUX (SSH + Hardening)
    # ==========================================
    linux_servers:
      children:
        debian_router:
        linux_vms:
      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_become: yes
        apply_ssh_hardening: yes
        apply_system_hardening: yes

    linux_vms:
      hosts:
        ubuntu-pc: {} # Hereda la configuración de vm_hosts y usa ssh.cfg

    # ==========================================
    # WINDOWS HOSTS (WinRM)
    # ==========================================
    windows_hosts:
      hosts:
        windows-pc:
          ansible_connection: winrm
      vars:
        apply_ssh_hardening: no
        apply_system_hardening: no

    # ==========================================
    # GRUPOS LÓGICOS (para roles específicos)
    # ==========================================
    # Nota: debian_router es el grupo principal para el router

    all_vms:
      children:
        vm_router:
        vm_hosts:
        
    all_ios:
      children:
        ios_routers:
        ios_switches: