---
all:
  children:
    esxi:
      hosts:
        esxi-vmware-host:
          ansible_host: "{{ vcenter_hostname }}"
          ansible_connection: local
          vcenter_hostname: "{{ vcenter_hostname }}"
          vcenter_username: "{{ vcenter_username }}"
          vcenter_password: "{{ vcenter_password }}"
          vcenter_port: "{{ vcenter_port }}"
          vcenter_validate_certs: "{{ vcenter_validate_certs }}"
          datacenter: ha-datacenter
          datastore: datastore1

    debian_router:
      hosts:
        debian-router:
          # --- Conexión Ansible ---
          # Se conecta por la IP de gestión, que es fija.
          ansible_host: "172.17.25.126"
          ansible_user: ansible
          ansible_connection: ssh
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5'
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_flags: '-S'
          ansible_ssh_timeout: 5
          ansible_timeout: 10

          # --- Configuración de VM ---
          vm_name: vm-debian-router
          vm_folder: "/vm"
          cdrom: "[datastore1] debian/debian-12.12.0-amd64-netinst.iso"
          
          # --- Configuración APT ---
          apt_force_ipv4: false  # No forzar IPv4 para APT ya que queremos usar IPv6
          # La VM debe tener 2 interfaces: una en 'VM Network' y otra en 'Red Fernandez'
          networks:
            - name: VM Network
            - name: Red Fernandez

          # --- Interfaz WAN (y Gestión) ---
          # Configuración inicial para permitir la conexión de Ansible
          ansible_initial_ip: "172.17.25.126"  # IP temporal para gestión inicial
          
          # Configuración final de WAN
          wan_method: "dhcp"  # Método de configuración: 'dhcp' o 'static'
          wan_interface: ens224  # Interfaz WAN en el router Debian (actualmente tiene 172.17.25.126)

          # --- Interfaz LAN ---
          # Conectada a "Red Fernandez". Da servicio a las VMs del laboratorio.
          lan_interface: ens192  # Interfaz LAN en el router Debian
          lan_ipv6_address: "2025:db8:101::1"
          lan_ipv6_prefix: 64

          # --- Servicios en la LAN ---
          # radvd y dhcpv6 para la subred 2025:DB8:101::/64
          radvd_prefix: "2025:db8:101::/64"
          dhcpv6_subnet: "2025:db8:101::"
          dhcpv6_prefix: 64
          dhcpv6_range_start: "2025:db8:101::100"
          dhcpv6_range_end: "2025:db8:101::200"
          dhcpv6_dns_servers:
            - "2001:4860:4860::8888"
            - "2001:4860:4860::8844"
          # Rutas estáticas IPv6 persistentes que se aplicarán en /etc/network/interfaces
          static_routes:
            - network: "2025:db8:100::/64"
              via: "2025:db8:101::1"

    vm_hosts:
      hosts:
        ubuntu-pc:
          ansible_host: "2025:db8:101::10"  # Nueva red unificada
          ansible_user: ansible
          ansible_connection: ssh
          vm_name: vm-ubuntu-pc
          vm_folder: "/vm"
          cdrom: "[datastore1] ubuntu/ubuntu-24.04.2-desktop-amd64.iso"
          networks:
            - name: Red Fernandez
              type: slaac  # Obtiene IP del Debian Router
              ipv6_expected: "2025:db8:101::10"
              ipv6_prefix: "64"

        windows-pc:
          ansible_host: "2025:db8:101::11"  # Nueva red unificada
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_transport: basic
          vm_name: vm-windows-pc
          vm_folder: "/vm"
          cdrom: "[datastore1] W-11/Win11_25H2_Spanish_Mexico_x64.iso"
          networks:
            - name: Red Fernandez
              type: slaac  # Obtiene IP del Debian Router
              ipv6_expected: "2025:db8:101::11"
              ipv6_prefix: "64"

    # ==========================================
    # DISPOSITIVOS DE RED (IOS/Network CLI)
    # ==========================================
    network_devices:
      children:
        ios_routers:
        ios_switches:
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_user: "{{ cisco_user }}"
        ansible_password: "{{ cisco_password }}"

    ios_routers:
      hosts:
        # Router físico del laboratorio
        physical-router:
          ansible_host: "2025:db8:101::2"  # Acceso por IPv6 (interfaz G0/0/1)
          hostname: "RouterLab"
          interfaces: "{{ physical_router_interfaces }}"
          static_routes:
            - network: "2025:db8:101::/64"
              via: "2025:db8:101::1"  # Ruta hacia debian-router
            - network: "2025:db8:100::/64"
              via: "2025:db8:100::1"  # Ruta local (connected)

    ios_switches:
      hosts:
        # NOTA: switch-3 es un puente L2 transparente sin gestión IP
        # No requiere configuración via Ansible - funciona como switch no gestionado

    # ==========================================
    # SERVIDORES LINUX (SSH + Hardening)
    # ==========================================
    linux_servers:
      children:
        debian_router:
        linux_vms:
      vars:
        ansible_connection: ssh
        ansible_user: ansible
        ansible_become: yes
        apply_ssh_hardening: yes
        apply_system_hardening: yes

    linux_vms:
      hosts:
        ubuntu-pc:
          ansible_host: "2025:db8:101::10"
          ansible_user: ansible
          ansible_connection: ssh

    # ==========================================
    # WINDOWS HOSTS (WinRM)
    # ==========================================
    windows_hosts:
      hosts:
        windows-pc:
          ansible_host: "2025:db8:101::11"
          ansible_user: Administrator
          ansible_connection: winrm
      vars:
        apply_ssh_hardening: no
        apply_system_hardening: no

    # ==========================================
    # GRUPOS LÓGICOS (para roles específicos)
    # ==========================================
    vm_router:
      children:
        debian_router:

    all_vms:
      children:
        vm_router:
        vm_hosts:
        
    all_ios:
      children:
        ios_routers:
        ios_switches: