---
# Role: vmware-windows
# Descripción: Crear y aprovisionar VM Windows PC en ESXi

- name: Eliminar VM existente si existe
  community.vmware.vmware_guest:
    hostname: "{{ hostvars['esxi-vmware-host']['vcenter_hostname'] }}"
    username: "{{ hostvars['esxi-vmware-host']['vcenter_username'] }}"
    password: "{{ hostvars['esxi-vmware-host']['vcenter_password'] }}"
    validate_certs: "{{ hostvars['esxi-vmware-host']['vcenter_validate_certs'] }}"
    name: "{{ vm_name }}"
    state: absent
    force: yes
  delegate_to: localhost
  become: false
  ignore_errors: yes

- name: Verificar conectividad con ESXi
  community.vmware.vmware_host_facts:
    hostname: "{{ hostvars['esxi-vmware-host']['vcenter_hostname'] }}"
    username: "{{ hostvars['esxi-vmware-host']['vcenter_username'] }}"
    password: "{{ hostvars['esxi-vmware-host']['vcenter_password'] }}"
    validate_certs: "{{ hostvars['esxi-vmware-host']['vcenter_validate_certs'] }}"
  register: esxi_facts
  delegate_to: localhost
  become: false

- name: Crear VM Windows PC desde ISO
  community.vmware.vmware_guest:
    hostname: "{{ hostvars['esxi-vmware-host']['vcenter_hostname'] }}"
    username: "{{ hostvars['esxi-vmware-host']['vcenter_username'] }}"
    password: "{{ hostvars['esxi-vmware-host']['vcenter_password'] }}"
    validate_certs: "{{ hostvars['esxi-vmware-host']['vcenter_validate_certs'] }}"
    datacenter: "{{ hostvars['esxi-vmware-host']['datacenter'] }}"
    name: "{{ vm_name }}"
    state: present
    folder: "{{ vm_folder }}"
    datastore: "{{ hostvars['esxi-vmware-host']['datastore'] }}"
    guest_id: "{{ guest_id | default('windows11_64Guest') }}"
    hardware:
      memory_mb: 8192
      num_cpus: 4
      scsi: paravirtual
      boot_firmware: "efi"
      version: 19
      nested_virt: true
      secure_boot: true
      tpm:
        - provider: "vtpm"
          version: "2.0"
    disk:
      - size_gb: 40
        type: thin
    cdrom:
      - controller_number: 0
        controller_type: ide
        type: iso
        iso_path: "{{ cdrom }}"
        state: present
        unit_number: 0
    networks:
      - name: "{{ networks[0].name }}"
    force: yes
  delegate_to: localhost
  become: false
  register: vm_facts

- name: Encender VM Windows para instalación
  community.vmware.vmware_guest:
    hostname: "{{ hostvars['esxi-vmware-host']['vcenter_hostname'] }}"
    username: "{{ hostvars['esxi-vmware-host']['vcenter_username'] }}"
    password: "{{ hostvars['esxi-vmware-host']['vcenter_password'] }}"
    validate_certs: "{{ hostvars['esxi-vmware-host']['vcenter_validate_certs'] }}"
    name: "{{ vm_name }}"
    state: poweredon
  delegate_to: localhost
  become: false

- name: Resumen de creación
  debug:
    msg:
      - "VM {{ vm_name }} creada exitosamente"
      - "Estado: Encendida para instalación desde ISO"
      - "ISO: {{ cdrom }}"
      - "NOTA: La instalación del SO debe completarse manualmente"
      - "Después de instalar, configurar IPv6: {{ networks[0].ipv6_address | default(networks[0].ipv6_expected | default('N/A')) }}/{{ networks[0].ipv6_prefix | default('64') }} (SLAAC)"
