---
# Playbook: Configurar Debian Router - Gateway IPv6 Central
# Descripción: Configura Debian como gateway IPv6 de la red 2025:DB8:101::/64
# Servicios: IPv6 Forwarding, RA (radvd), DHCPv6, HTTP, FTP, Firewall
# Interfaces: ens160 (gestión 172.17.25.10) + ens192 (proyecto 2025:DB8:101::1)

- name: "⭐ Configurar Debian Router - Gateway IPv6 Central"
  hosts: debian_router
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: "📝 Mostrar información del host"
      debug:
        msg:
          - "========================================"
          - "  Configurando Debian Router"
          - "========================================"
          - "Host: {{ inventory_hostname }}"
          - "IPv6: {{ lan_ipv6_address }}/{{ lan_ipv6_prefix }}"
          - "Gestión IPv4: {{ wan_mgmt_ipv4 }}"
          - "Interfaz Proyecto: {{ lan_interface }}"
          - "Interfaz Gestión: {{ wan_interface }}"
          - "Red: {{ radvd_prefix }}"
          - "========================================"
  
  tasks:
    - name: "📦 Aplicar role: debian-ipv6-router"
      include_role:
        name: debian-ipv6-router
      tags:
        - router
        - ipv6
        - network
  
  post_tasks:
    - name: "✅ Configuración completada exitosamente"
      debug:
        msg:
          - "========================================"
          - "  ✅ Debian Router Configurado"
          - "========================================"
          - ""
          - "Red: {{ radvd_prefix }}"
          - "Gateway: {{ lan_ipv6_address }}/{{ lan_ipv6_prefix }}"
          - ""
          - "Interfaces:"
          - "  - {{ wan_interface }}: {{ wan_mgmt_ipv4 }} (Gestión)"
          - "  - {{ lan_interface }}: {{ lan_ipv6_address }} (Proyecto)"
          - ""
          - "DHCPv6 Pool: {{ dhcpv6_range_start }} - {{ dhcpv6_range_end }}"
          - "DNS Servers: {{ dhcpv6_dns_servers | join(', ') }}"
          - ""
          - "Acceso:"
          - "  - SSH (Gestión): ssh ansible@{{ wan_mgmt_ipv4 }}"
          - "  - SSH (IPv6): ssh ansible@[{{ lan_ipv6_address }}]"
          - "  - HTTP: http://[{{ lan_ipv6_address }}]"
          - "  - FTP: ftp://[{{ lan_ipv6_address }}]"
          - ""
          - "Verificar servicios:"
          - "  systemctl status radvd"
          - "  systemctl status isc-dhcp-server6"
          - "  systemctl status apache2"
          - "  systemctl status vsftpd"
          - "  systemctl status nftables"
          - ""
          - "Verificar red:"
          - "  ip -6 addr show {{ lan_interface }}"
          - "  ip -6 route"
          - "  ping6 -c4 2001:4860:4860::8888"
          - "========================================"
